apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-vivo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto-vivo
  template:
    metadata:
      labels:
        app: projeto-vivo
    spec:
      containers:
        - name: projeto-vivo-container
          image: projeto-vivo-img:latest
          ports:
            - containerPort: 3000
          env:
            - name: NAME
              value: $(NAME)
